# This is a basic workflow to invoke a Trivy Container Scan on your project container image

name: Vulnerability Scan

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, security/* ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "scan"
  scan:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Trufflehog3 Secret Scan and Report Parser
        uses: netlify/security-netlify-trufflehog3@v0.6.0
        with:
          trufflehog_report_file_path: 'trufflehog_report.json'
          suppression_file_path: '.github/workflows/trufflehog3-files/suppressions-trufflehog3'
          ignore_paths_file_path: '.github/workflows/trufflehog3-files/ignore-paths-trufflehog3'
          create_github_issue: 'true'
          create_slack_notification: 'false'
          secret_scan_slack_webhook: ${{ secrets.SECRET_SCAN_SLACK_WEBHOOK }}
          secret_scan_gh_access_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo_name: ${{ github.repository}}
          github_server: ${{ github.server_url }}
